#ifndef __SW_HEADER_H
#define __SW_HEADER_H
#include "station_orv32.h"
#include "station_cache.h"
#include "station_slow_io.h"
#include "station_sdio.h"
#include "station_dma.h"
#include "station_flash.h"

enum clk_rst_enum {
  BLOCK_TEST_IO,
  BLOCK_JTAG2OR,
  BLOCK_ORV32,
  BLOCK_DMA,

  BLOCK_BANK,
  BLOCK_FLASH_CTRL,
  BLOCK_SDIO,
  BLOCK_SSP,

  BLOCK_STATION,
  BLOCK_CPU_NOC,
  BLOCK_SSPIM0,
  BLOCK_SSPIM1,

  BLOCK_SSPIM2,
  BLOCK_SPIS,
  BLOCK_I2C0,
  BLOCK_I2C1,

  BLOCK_I2C2,
  BLOCK_UART0,
  BLOCK_UART1,
  BLOCK_UART2,

  BLOCK_UART3,
  BLOCK_I2SM,
  BLOCK_I2SS0,
  BLOCK_GPIO,

  BLOCK_TIMERS,
  BLOCK_RTC,
  BLOCK_WDT,
  BLOCK_BOOTUP_FSM,

  BLOCK_APB_TIMER,
  BLOCK_ADC,
  CLK_DM_MAX
};

enum power_domain_enum {
  SYS_POWER_DOMAIN,
  SRAM_POWER_DOMAIN_0, // 0k-8k
  SRAM_POWER_DOMAIN_1, // 8k-16k
  SRAM_POWER_DOMAIN_2, // 16k-24k
  SRAM_POWER_DOMAIN_3, // 24k-32k
  SRAM_POWER_DOMAIN_4, // 32k-40k
  SRAM_POWER_DOMAIN_5, // 40k-48k
  SRAM_POWER_DOMAIN_6, // 48k-56k
  SRAM_POWER_DOMAIN_7, // 56k-64k
  TAG_RAM_POWER_DOMAIN,
  PERIPH_POWER_DOMAIN,
  POWER_DM_MAX
};

enum intr_src_enum {
  QSPIM_INTR,
  SSPIM0_INTR,
  SSPIM1_INTR,
  SSPIM2_INTR,
  SPIS_INTR,
  UART0_INTR,
  UART1_INTR,
  UART2_INTR,
  UART3_INTR,
  I2SM_INTR,
  I2SS0_INTR,
  I2C0_INTR,
  I2C1_INTR,
  I2C2_INTR,
  GPIO_INTR,
  TIMERS_INTR,
  RTC_INTR,
  WDT_INTR,
  SDIO_INTR,
  SDIO_WAKEUP_INTR,
  POWER_CTRL_INTR,
  DMA_THREAD0_INTR,
  DMA_THREAD1_INTR,
  DMA_THREAD2_INTR,
  DMA_THREAD3_INTR,
  APB_TIMER0_INTR,
  APB_TIMER1_INTR,
  ADC_INTR,
  NUM_IRQ_EXT_MAX
};

enum gpio_addr_enum {
  GPIO_DR_ADDR_0             = 0x4003400,
  GPIO_DR_ADDR_1             = 0x4003404,
  GPIO_DDR_ADDR_0            = 0x4003408,
  GPIO_DDR_ADDR_1            = 0x400340c,
  GPIO_INTEN_ADDR_0          = 0x4003410,
  GPIO_INTEN_ADDR_1          = 0x4003414,
  GPIO_INT_POLARITY_ADDR_0   = 0x4003418,
  GPIO_INT_POLARITY_ADDR_1   = 0x400341c,
  GPIO_INTMASK_ADDR_0        = 0x4003420,
  GPIO_INTMASK_ADDR_1        = 0x4003424,
  GPIO_INTTYPE_LEVEL_ADDR_0  = 0x4003428,
  GPIO_INTTYPE_LEVEL_ADDR_1  = 0x400342c,
  GPIO_INTSTATUS_ADDR_0      = 0x4003430,
  GPIO_INTSTATUS_ADDR_1      = 0x4003434,
  GPIO_RAW_INTSTATUS_ADDR_0  = 0x4003438,
  GPIO_RAW_INTSTATUS_ADDR_1  = 0x400343c,
  GPIO_EOI_ADDR_0            = 0x4003440,
  GPIO_EOI_ADDR_1            = 0x4003444,
  GPIO_DEBOUNCE_ADDR_0       = 0x4003448,
  GPIO_DEBOUNCE_ADDR_1       = 0x400344c,
  GPIO_EXT_PORTA_ADDR_0      = 0x4003450,
  GPIO_EXT_PORTA_ADDR_1      = 0x4003454,
  GPIO_VER_ID_CODE_ADDR      = 0x4003458
};

enum dma_intr_src {
  DMA_RESERVED,
  DMA_QSPIM_INTR,
  DMA_I2SS0_INTR,
  DMA_I2SM_INTR,
  DMA_SSPIM0_INTR,
  DMA_SSPIM1_INTR,
  DMA_SSPIM2_INTR,
  DMA_SPIS_INTR,
  DMA_UART0_INTR,
  DMA_UART1_INTR,
  DMA_UART2_INTR,
  DMA_UART3_INTR,
  DMA_I2C0_INTR,
  DMA_I2C1_INTR,
  DMA_I2C2_INTR
};

#define SSP_SHARED_SEL_0_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_0
#define SSP_SHARED_SEL_1_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_1
#define SSP_SHARED_SEL_2_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_2
#define SSP_SHARED_SEL_3_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_3
#define SSP_SHARED_SEL_4_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_4
#define SSP_SHARED_SEL_5_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_5
#define SSP_SHARED_SEL_6_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_6
#define SSP_SHARED_SEL_7_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_7
#define SSP_SHARED_SEL_8_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_8
#define SSP_SHARED_SEL_9_ADDR 	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_9
#define SSP_SHARED_SEL_10_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_10
#define SSP_SHARED_SEL_11_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_11
#define SSP_SHARED_SEL_12_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_12
#define SSP_SHARED_SEL_13_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_13
#define SSP_SHARED_SEL_14_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_14
#define SSP_SHARED_SEL_15_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_15
#define SSP_SHARED_SEL_16_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_16
#define SSP_SHARED_SEL_17_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_17
#define SSP_SHARED_SEL_18_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_18
#define SSP_SHARED_SEL_19_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_19
#define SSP_SHARED_SEL_20_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_20
#define SSP_SHARED_SEL_21_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_21
#define SSP_SHARED_SEL_22_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_22
#define SSP_SHARED_SEL_23_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_23
#define SSP_SHARED_SEL_24_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_24
#define SSP_SHARED_SEL_25_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_25
#define SSP_SHARED_SEL_26_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_26
#define SSP_SHARED_SEL_27_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_27
#define SSP_SHARED_SEL_28_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_28
#define SSP_SHARED_SEL_29_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_29
#define SSP_SHARED_SEL_30_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_30
#define SSP_SHARED_SEL_31_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_31
#define SSP_SHARED_SEL_32_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_32
#define SSP_SHARED_SEL_33_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_33
#define SSP_SHARED_SEL_34_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_34
#define SSP_SHARED_SEL_35_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_35
#define SSP_SHARED_SEL_36_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_36
#define SSP_SHARED_SEL_37_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_37
#define SSP_SHARED_SEL_38_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_38
#define SSP_SHARED_SEL_39_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_39
#define SSP_SHARED_SEL_40_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_40
#define SSP_SHARED_SEL_41_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_41
#define SSP_SHARED_SEL_42_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_42
#define SSP_SHARED_SEL_43_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_43
#define SSP_SHARED_SEL_44_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_44
#define SSP_SHARED_SEL_45_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_45
#define SSP_SHARED_SEL_46_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_46
#define SSP_SHARED_SEL_47_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_47
#define SSP_SHARED_SEL_48_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_48
#define SSP_SHARED_SEL_49_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_49
#define SSP_SHARED_SEL_50_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_50
#define SSP_SHARED_SEL_51_ADDR	STATION_SLOW_IO_SCU_SSP_SHARED_SEL_ADDR__DEPTH_51

#define UART1_TX_PIN SSP_SHARED_SEL_23_ADDR
#define UART1_RX_PIN SSP_SHARED_SEL_24_ADDR
#endif
